<?php
    $products = $this->getProducts();
    $token = $this->getToken();
    $token2 = $this->getToken2();
    $storeId = $this->getStoreId();
    $id = $this->getId();
?>
<table cellspacing="0" cellpadding="0" border="0" width="650" style="border:1px solid #EAEAEA;">
    <?php foreach($products as $product): ?>
    <tr>
        <?php $parentId = Mage::getModel('catalog/product_type_configurable')->getParentIdsByChild($product->getId());
              if(isset($parentId[0])) {
                  $product = Mage::getModel('catalog/product')->load($parentId[0]);
              }

              $url = Mage::getModel('core/url')->setStore($storeId)->getUrl().'ebizautoresponder/autoresponder/loadquote?itemId='.$product->getId();


              //$url = Mage::getStoreConfig(Ebizmarts_Autoresponder_Model_Config::PAGE,$storeId);
              /*if ($url == 'review/product/list/'){
                  $url .= 'id/'.$product->getId();
              }*/
              if($token2){
                  $url .= '&token2='.$token2.'&id='.$id.'&storeId='.$storeId;
              }
              if($token) {
                  $url .= '&token='.$token;
              }
        ?>
            <td valign="top" align="left" style="padding:3px 9px"><a href="<?php echo $url; ?>" alt="<?php echo $this->escapeHtml($product->getName()); ?>" target="_blank"><img src="<?php echo $product->getThumbnailUrl();?>" alt="<?php echo $this->escapeHtml($product->getName()); ?>"/></a></td>
            <td valign="top" align="left" style="padding:3px 9px"><p><h2><a href="<?php echo $url; ?>"> Santiago Rate <?php echo $this->escapeHtml($product->getName()); ?></a></h2></p><?php echo $this->escapeHtml($product->getShortDescription()); ?></td>
    </tr>
    <?php endforeach; ?>
</table>